---
title: "Detailed Explanations of SalarHybPower"
output: 
  html_document:
    toc: false
    toc_flaot: false

---

Here are links to a series of pages about the development and use of the 
SalarHybPower R package.

## Getting the repository

To reproduce these analyses you need to 

1. Get the repository at
[https://github.com/eriqande/SalarHybPower](https://github.com/eriqande/SalarHybPower).  This 
is still a private repo, but will be made public as soon as I learn that it is OK to release the 
SNP array data that is in it.  
2. That repo is an Rstudio project for an Rpackage.  Build the package.
3. Run all the notebooks (and shell commands within them...) listed below from the 
root directory of the repository.  

Have fun. Questions to eric.anderson@noaa.gov

## Preparing a "pseudo" linkage map

- [dev-01-initial-data-maneuvers.nb.html](./dev-01-initial-data-maneuvers.nb.html) --- How I went about making a sex-averaged linkage map and "sprinkling" unmapped markers into it.  I was originally thinking I was going to write this to PLINK format, but discovered I could do things better and just as quickly in a tidy format.


## Actually doing the analyses for the paper

- [doing-it-01-big-runs-newfoundland.nb.html](./doing-it-01-big-runs-newfoundland.nb.html) --- A notebook showing the steps taken to actually to the whole big run for the Newfoundland data set.
- [doing-it-summarizing-newfoundland-big-runs.nb.html](./doing-it-summarizing-newfoundland-big-runs.nb.html) --- Summarizing
the Newfoundland runs. Computing accuracy and efficiency and also computing ROC curves.
- [doing-it-02-big-runs-maritimes.nb.html](./doing-it-02-big-runs-maritimes.nb.html) --- A notebook showing the steps taken to actually to the whole big run for the Maritimes data set.
- [doing-it-summarizing-maritimes-big-runs.nb.html](./doing-it-summarizing-maritimes-big-runs.nb.html) --- Summarizing
the Maritimes runs. Computing accuracy and efficiency and also computing ROC curves.

## Various steps and functions in SalarHybPower

Some notebooks I put together while developing SalarHybPower for those that want
to know the gory details.

- [dev-02-selecting-individuals-and-loci.nb.html](./dev-02-selecting-individuals-and-loci.nb.html) --- How the training and test data sets are formed and the ranking criterion used for loci.
- [dev-03-utilities-for-making-newhybs-files.nb.html](./dev-03-utilities-for-making-newhybs-files.nb.html) --- An overview of a few helpful functions to quickly write out newhybrids files.
- [dev-04-segregation-and-reproduction.nb.html](./dev-04-segregation-and-reproduction.nb.html) --- This notebook documents the strategy for segregating linked markers from individuals and forming hybrids. It lists a few functions to do this.
- [dev-05-putting-it-all-together.nb.html](./dev-05-putting-it-all-together.nb.html) --- This notebook documents the development of the strategy for putting together all the previous functions so that we can start from a data set of individual genotypes and physical positions and then I can do:
    1. Choose train and test
    2. Rank markers
    3. Simulate data sets with different types of hybrids
    4. Write those data sets out in a directory structure that makes it easy to run newhybrids with Unix parallel.
    
- [dev-06-testing-seg-funcs.nb.html](./dev-06-testing-seg-funcs.nb.html) --- Some brief testing done to make sure that the segregation was done correctly.
- [dev-07-make-multiple-data-sets.nb.html](./dev-07-make-multiple-data-sets.nb.html) --- How to make multiple simulated data sets.
- [dev-08-make-multiple-data-sets-pop-specific-reference.nb.html](./dev-08-make-multiple-data-sets-pop-specific-reference.nb.html) --- Experimenting with using as a reference data set (with the z option in newhybrids) only those
training individuals that were from the same wild population that was being tested.  This is not how we ended up doing things in the Salar SNP Panel paper.

